# this file is *not* meant to cover or endorse the use of travis, but rather to
# help confirm pull requests to this project.

language: python

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y portaudio-devel python-devel gcc

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.4
      - python3.5

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36

install: pip install tox

script: tox

notifications:
  email: false
