# this file is *not* meant to cover or endorse the use of travis, but rather to
# help confirm pull requests to this project.

language: python

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gcc portaudio19-dev

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36

install: pip install tox

script: tox

notifications:
  email: false
